#!/bin/sh
# Deploy the Vector Drift download proxy, stamped with the commit it was built
# from.
#
# Use this instead of `wrangler deploy`. version.js is generated here and is
# gitignored, so a bare `wrangler deploy` fails on the missing import rather
# than shipping a build whose /health lies about what it is running.
#
# The reason this exists: a stale deploy is invisible. Three separate wrong
# diagnoses in one day traced back to source that was correct in the working
# tree and absent from production, and each cost hours because "is the live
# code current" could only be answered by eyeballing a dashboard. Now:
#
#     curl -s https://vd-dl-proxy.codexjr.workers.dev/health
#
# answers it in a second.
set -e
cd "$(dirname "$0")"

sha=$(git rev-parse --short HEAD)
if [ -n "$(git status --porcelain -- . ':!version.js')" ]; then
  sha="$sha-dirty"
fi
built=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > version.js <<JS
// GENERATED by deploy.sh. Not committed; edits here are overwritten.
export const BUILD = { commit: "$sha", built: "$built" };
JS

echo "deploying vd-dl-proxy  commit=$sha  built=$built"
npx wrangler deploy
echo
echo "verify:  curl -s https://vd-dl-proxy.codexjr.workers.dev/health"
